# Meta Data for SEO

## Homepage
title = "RKVST"
titleSeparator = "-"
titleAddition = "Continuous Assurance to boost confidence in critical decisions."
description = "RKVST provides Continuous Assurance as a Service to attest trustworthiness of assets, and boost confidence in critical decisions.  Find out more on our [website](https://rkvst.com)."

## Open Graph + Twitter Cards
images = ["RKVST_WhtLogo_CMYK.svg"]
twitterSite = ""
twitterCreator = ""
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "RKVST_BlueTick_RBG.png"
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/rkvst"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 100
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 500, 200]
portraitPhotoWidths = [900, 800, 500]
lqipWidth = "100x"

# Footer
footer = "Powered by <a href=\"https://gohugo.io/\">Hugo</a> and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://www.github.com/rkvst/rkvst-docs"
editPage = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = false
  collapsibleSidebar = true