name = "Jitsuin RKVST"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Multi-Party Trust Automation API, Powered by Blockchain "
homepage = "https://jitsuin.com/"
tags = ["landing page", "documentation", "jitsuin", "blockchain", "multiparty", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
min_version = "0.75.0"

[author]
  name = "Will Godfrey"
